fix: OpenAPI validation errors
the OpenApiControllerTest failed with

```
 org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
   | Error count: 8, Warning count: 1
  Errors:
      -paths.'/api/dataElementOperands/'(get).parameters. There are duplicate parameter values
      -paths.'/api/organisationUnits/'(get).parameters. There are duplicate parameter values
      -paths.'/api/organisationUnits/{uid}/children'(get).parameters. There are duplicate parameter values
      -paths.'/api/organisationUnits/#getObjectListCsv'(get).parameters. There are duplicate parameter values
      -paths.'/api/organisationUnits/{uid}/parents'(get).parameters. There are duplicate parameter values
      -paths.'/api/organisationUnits/{uid}'(get).parameters. There are duplicate parameter values
      -paths.'/api/organisationUnits/{uid}/ancestors'(get).parameters. There are duplicate parameter values
      -paths.'/api/organisationUnits/{uid}/descendants'(get).parameters. There are duplicate parameter values
  Warnings:
      -paths.'/api/dataElementOperands/'(get).parameters. There are duplicate parameter values
      -paths.'/api/organisationUnits/'(get).parameters. There are duplicate parameter values
      -paths.'/api/organisationUnits/{uid}/children'(get).parameters. There are duplicate parameter values
      -paths.'/api/organisationUnits/#getObjectListCsv'(get).parameters. There are duplicate parameter values
      -paths.'/api/organisationUnits/{uid}/parents'(get).parameters. There are duplicate parameter values
      -paths.'/api/organisationUnits/{uid}'(get).parameters. There are duplicate parameter values
      -paths.'/api/organisationUnits/{uid}/ancestors'(get).parameters. There are duplicate parameter values
      -paths.'/api/organisationUnits/{uid}/descendants'(get).parameters. There are duplicate parameter values

      at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:717)
      at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:744)
      at org.hisp.dhis.webapi.controller.OpenApiControllerTest.testGetOpenApiDocument_CodeGeneration(OpenApiControllerTest.java:256)
      at java.base/java.lang.reflect.Method.invoke(Method.java:569)
      at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
      at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

it was not clear what the actual issue is. Running this spec validator
on the entire spec generated via the OpenApiTool

```sh
go run github.com/pb33f/libopenapi-validator/cmd/validate@latest local.json
```

showed the issue was that references to these properties were generated

for the above controller methods/endpoints.

The properties filters/orders have a `@JsonProperty` which makes the
parameter name singular. The getters have a `@OpenApi.Ignore` but the
setters created by lombok did not. Adding them resolves the issue.