chore: improve error message for invalid filter value type
```http
GET {{PROTOCOL}}://{{AUTH}}@{{HOST}}/api/tracker/events?
  program=VBqh0ynB2wv&
  fields=dataValues[dataElement,value]&
  filter=qrur9Dvnyt5:gt:foo
```

lead to `409 Query failed because of a syntax error (SqlState: 07006)`
if the data element value type is numeric. We did cast the user provided
value for data elements to numeric in the SQL. This lead to

```sh
 org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [...]
 ...
  Caused by: org.postgresql.util.PSQLException: Cannot convert an instance of java.lang.String to type BigDecimal
       at org.postgresql.jdbc.PgPreparedStatement.cannotCastException(PgPreparedStatement.java:980) ~[postgresql-42.7.5.jar:42.7.5]
       at org.postgresql.jdbc.PgPreparedStatement.castToBigDecimal(PgPreparedStatement.java:952) ~[postgresql-42.7.5.jar:42.7.5]
       at org.postgresql.jdbc.PgPreparedStatement.setObject(PgPreparedStatement.java:611) ~[postgresql-42.7.5.jar:42.7.5]
       at org.postgresql.jdbc.PgPreparedStatement.setObject(PgPreparedStatement.java:987) ~[postgresql-42.7.5.jar:42.7.5]
       at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.setObject(NewProxyPreparedStatement.java:249) ~[c3p0-0.11.0-pre2.jar:?]
       at org.springframework.jdbc.core.StatementCreatorUtils.setValue(StatementCreatorUtils.java:378) ~[spring-jdbc-6.2.3.jar:6.2.3]
       at org.springframework.jdbc.core.StatementCreatorUtils.setParameterValueInternal(StatementCreatorUtils.java:247) ~[spring-jdbc-6.2.3.jar:6.2.3]
       at org.springframework.jdbc.core.StatementCreatorUtils.setParameterValue(StatementCreatorUtils.java:163) ~[spring-jdbc-6.2.3.jar:6.2.3]
       at org.springframework.jdbc.core.PreparedStatementCreatorFactory$PreparedStatementCreatorImpl.setValues(PreparedStatementCreatorFactory.java:287) ~[spring-jdbc-6.2.3.jar:6.2.3]
       at org.springframework.jdbc.core.PreparedStatementCreatorFactory$PreparedStatementCreatorImpl.createPreparedStatement(PreparedStatementCreatorFactory.java:245) ~[spring-jdbc-6.2.3.jar:6.2.3]
       at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:656) ~[spring-jdbc-6.2.3.jar:6.2.3]
       ... 174 more
 Caused by: java.lang.NumberFormatException: Character f is neither a decimal digit number, decimal point, nor "e" notation exponential mark.
       at java.base/java.math.BigDecimal.<init>(Unknown Source) ~[?:?]
       at java.base/java.math.BigDecimal.<init>(Unknown Source) ~[?:?]
       at java.base/java.math.BigDecimal.<init>(Unknown Source) ~[?:?]
       at org.postgresql.jdbc.PgPreparedStatement.castToBigDecimal(PgPreparedStatement.java:926) ~[postgresql-42.7.5.jar:42.7.5]
       at org.postgresql.jdbc.PgPreparedStatement.setObject(PgPreparedStatement.java:611) ~[postgresql-42.7.5.jar:42.7.5]
       at org.postgresql.jdbc.PgPreparedStatement.setObject(PgPreparedStatement.java:987) ~[postgresql-42.7.5.jar:42.7.5]
       at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.setObject(NewProxyPreparedStatement.java:249) ~[c3p0-0.11.0-pre2.jar:?]
       at org.springframework.jdbc.core.StatementCreatorUtils.setValue(StatementCreatorUtils.java:378) ~[spring-jdbc-6.2.3.jar:6.2.3]
       at org.springframework.jdbc.core.StatementCreatorUtils.setParameterValueInternal(StatementCreatorUtils.java:247) ~[spring-jdbc-6.2.3.jar:6.2.3]
       at org.springframework.jdbc.core.StatementCreatorUtils.setParameterValue(StatementCreatorUtils.java:163) ~[spring-jdbc-6.2.3.jar:6.2.3]
       at org.springframework.jdbc.core.PreparedStatementCreatorFactory$PreparedStatementCreatorImpl.setValues(PreparedStatementCreatorFactory.java:287) ~[spring-jdbc-6.2.3.jar:6.2.3]
       at org.springframework.jdbc.core.PreparedStatementCreatorFactory$PreparedStatementCreatorImpl.createPreparedStatement(PreparedStatementCreatorFactory.java:245) ~[spring-jdbc-6.2.3.jar:6.2.3]
       at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:656) ~[spring-jdbc-6.2.3.jar:6.2.3]
```

Interestingly, we did parse the user provided attribute value for
`filterAttributes`. Use the same approach for data values as well. Catch
the numeric exception and add some details so we now return a 400 with

`Filter for data element qrur9Dvnyt5 is invalid. The data element value type is numeric but the value 'foo' is not.`

(or `attribute` instead of `data element`).